#!/usr/bin/python3

# Prompt the user to enter the word
word = input("Enter a word: ").lower()

# input from the vowels
vowels = "aeiou"

# consonants
consonants = ""
i = 0

while i < len(word):
    if word[i] not in vowels and word[i] != "y":
        consonants += word[i] + ", "
    i += 1

print("The consonants in the word : " + consonants[:-2])

